version: "3.7"

volumes:
  advanced_testing_techniques_gem_bundle:
  advanced_testing_techniques_node_modules:
  advanced_testing_techniques_vs_code_server:

services:
  advanced_testing_techniques: &app_config
    image: icalialabs/advanced_testing_techniques:development
    build:
      context: .
      target: development
      args:
        DEVELOPER_UID: ${UID:-1000}
        DEVELOPER_USERNAME: ${USER:-you}
    volumes:
      - .:/usr/src # Mount the whole workspace directory
      - ~/.gnupg:/usr/src/.gnupg:ro
      - advanced_testing_techniques_gem_bundle:/usr/local/bundle
      - advanced_testing_techniques_node_modules:/usr/src/node_modules
      - advanced_testing_techniques_vs_code_server:/usr/src/.vscode-server
    stdin_open: true
    tty: true

    depends_on:
      - postgres
      - redis
      - advanced_testing_techniques_webpacker
    ports:
      - ${ADVANCED_TESTING_TECHNIQUES_WEB_PORT:-3000}:3000

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

    environment:
      # We'll set the DATABASE_URL environment variable for the app to connect
      # to our postgres container - no need to use a 'config/database.yml' file.
      DATABASE_URL: postgres://postgres:3x4mpl3P455w0rd@postgres:5432

      # We'll set the RAILS_ENV and RACK_ENV environment variables to
      # 'development', so our app containers will start in 'development' mode
      # on this compose project:
      RAILS_ENV: development
      RACK_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      MAILER_HOST: localhost
      MAILER_PORT: 3000
      LISTEN_USE_POLLING: ${ADVANCED_TESTING_TECHNIQUES_LISTEN_USE_POLLING:-no}
      REDIS_URL: redis://redis:6379/1

      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_BUCKET_NAME: icalia-advanced-testing-techniques
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      AWS_REGION: ${ADVANCED_TESTING_TECHNIQUES_AWS_REGION:-us-west-2}

      WEBPACKER_DEV_SERVER_HOST: advanced_testing_techniques_webpacker
      VSCODE_CONTEXT: "yes"

  advanced_testing_techniques_webpacker:
    <<: *app_config
    ports:
      - ${ADVANCED_TESTING_TECHNIQUES_WEBPACKER_DEV_SERVER_PORT:-3035}:3035
    entrypoint: /usr/src/bin/dev-entrypoint.sh
    depends_on: []
    command: webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
